version: 2

sources:
  - name: aqi_source
    database: AQI
    schema: DEV
    tables:
      - name: raw_aqi_data  
        description: "Raw data for Air Quality Index (AQI) measurements"
        loaded_at_field: record_ts
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
          # dbt source freshness --select source:AQI_SOURCE.RAW_AQI_DATA
models:
  - name: clean_aqi_data
    description: "Cleansed data for Air Quality Index (AQI) from various locations"
    columns:
      - name: RECORD_TS
        description: Timestamp of AQI measurement
        tests:
          - not_null
      - name: LATITUDE
        description: Latitude of the measurement station
        tests:
          - not_null
      - name: LONGITUDE
        description: Longitude of the measurement station
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['RECORD_TS', 'LATITUDE', 'LONGITUDE']
  - name: fact_aqi
    description: "Fact table for Air Quality Index (AQI) measurements"
    columns:
      - name: RECORD_PK
        description: Primary key for the AQI record
        tests:
          - not_null
          - unique
      - name: DATE_FK
        description: Foreign key to the measurement time dimension
        tests:
          - not_null
      - name: LOCATION_FK
        description: Foreign key to the measurement station dimension
        tests:
          - not_null
  - name: dim_locations
    description: measurement stations dimension table.
    columns:
      - name: location_pk
        description: Primary key for the location
        tests:
          - not_null
          - unique
  - name: dim_measurement_time
    description: hourly measurement time dimension table.
    columns:
      - name: date_pk
        description: Primary key for the measurement time
        tests:
          - not_null
          - unique